### ISSUE TITLE
Negative values

### ISSUE THREAD

**Issue by jmcollin78** [hif2k1/battery_sim#116]
Hello,

I install your wonderfull integration and I wonder why I've got the total `sensor.battery_sim_enphase_3t_2nd_gen_total_money_saved` as a negative number.

All energy sensor are positive in my configuration. Should export be negative ?

**Comment by hif2k1** [comment]
Money saved can be negative especially early on. As the battery charges for the first time it will use electricity you would have been paid for exporting. If it hasn't discharged much yet to save you on importing you will have a negative money saved. Alternatively you may have set the tariffs so that the export value was higher than the import you will also lose money or if you force it to charge from the grid. 
If you still think it is incorrect then please post your exact setup (tariffs etc). Many thanks.
