### ISSUE TITLE
Energy Saved Today

### ISSUE THREAD

**Issue by mikeykau** [hif2k1/battery_sim#14]
Hi,
Might be more of a question than issue.
How is energy saved today calculated? Is it based on when energy is stored, or when it is used from the battery?
Each day from midnight when the battery is discharging, it shows 0kWh saved today even though it has discharged by several kWh from midnight through until the morning.

<img width="392" alt="Screen Shot 2022-01-21 at 9 43 49 am" src="https://user-images.githubusercontent.com/39424064/150638254-9c1e13b5-f8ec-4b80-a4dd-0037c3972e85.png">

**Comment by hif2k1** [comment]
Hi there, thanks for the question.

The energy saved counters count energy released from the battery i.e. energy that would have otherwise been imported from the grid. There is a round trip inefficiency (some energy is lost charging and discharging) so measuring energy going into the battery wouldn't reflect savings accurately.

The "Energy saved today" does reset each day at midnight as you say. I suppose there are lots of possible time periods you could measure and resetting at midnight is fairly arbitrary. I think this aligns best with the breakdowns you get from energy companies and things which is why I chose this time to reset the counters. If you want to count energy saved over the last 24 hours or another time period you could use the statistics integration to do that. 

Thanks
