### ISSUE TITLE
Feature Request, cycle count

### ISSUE THREAD

**Issue by Jeffaffa** [hif2k1/battery_sim#62]
Hi,

Most batteries have a certain amount of battery cycles in them.
Is it possible to simulate this as well?

**Comment by hif2k1** [comment]
That is a good idea. Would you consider a full charge and full discharge to
be one cycle? i.e. is the number of cycles = total energy going through the
battery / battery capacity? It is hard because obviously most o the time
the battery might only partially charge and partially discharge. Not sure
how this is calculated in a real battery and whether they have easy of
spreading the wear across the cells.

**Comment by hif2k1** [comment]
I have added a cycle counter in the latest release. Hope it works ok for you.

**Comment by Jeffaffa** [comment]
Thanks! I wanted to ask if it is possible to have a second export sensor. In the weekends i switch to a low tariff and the sim stops during that time and starts again on monday. Shall i make a new request for that?
