### ISSUE TITLE
Problem during configuration

### ISSUE THREAD

**Issue by emics** [hif2k1/battery_sim#77]
Hi,
I have some problem during configuration.
I have **AEON Labs ZW095**  zwave device with 3 clamp and i have mount them in my house in this way:

- 1 clamp line from producer energy counter
- 1 clamp line from Solar panel
- 1 clamp line to House

each  clamp in HA have two sensor:
- energy 
- power

the first clamp measure **Power** positive value (when I buy) and negative value (when i sell)  and  the **Energy** sensor Increase when i buy and decrese when i sell Energy.

how can i use correctly your integration? i cant' find the right way, I have also created some sensor derivated from the original ones but without success.

thanks in advance.
Emiliano

**Comment by emics** [comment]
I'have created the right sensor now, but why the charging rate have big up and down when my export energy is so fluid ?

![image](https://github.com/hif2k1/battery_sim/assets/1004363/cd1a827c-4acf-4e49-b588-80cdb6a611ae)

**Comment by hif2k1** [comment]
Hi there,

Thanks for getting in touch. I did wonder if anyone would have this sort of setup - a single meter that goes up and down, but you are the first person I've come across with it. The battery configuration options are already very complicated so I didn't want to add yet more options, but we could look to add this in future. As you say though the work around is to make your own sensors/helpers that separate out the two parts.

As for the variation in the charging rate, that has come up before. It averages out over time to give the correct overall reading, but it does look untidy. It is to do with the battery not necessarily updating on the same frequency as the export sensor so that in one cycle it measures a bit more energy and the next a bit less. It's hard to solve this problem as the battery needs to respond to both import and export readings. One option would be to update less frequently to average out the readings, but then you might lose some of the more granular data and might lose some energy savings so it's a trade off. Any opinions on how to resolve that trade off are welcome.

Many thanks,

Hamish
