### ISSUE TITLE
Add total value of energie saved

### ISSUE THREAD

**Issue by maikrolf** [hif2k1/battery_sim#8]
Is it possible to add an option so we can see what battery is the best in how much it actualy saves in money?

there is a saved persentage on the addon but it can not be read outside the addon.

**Comment by YMGV** [comment]
> Is it possible to add an option so we can see what battery is the best in how much it actualy saves in money?
> 
> there is a saved persentage on the addon but it can not be read outside the addon.

- platform: template
  sensors: 
      energie_bespaard: 
        friendly_name: "Energie bespaard"
        unit_of_measurement: 'kWh'
        value_template: "{{ state_attr('sensor.lg_chem', 'energy_saved') |float | round (0) }}"
        icon_template: mdi:battery-sync-outline

**Comment by maikrolf** [comment]
@YMGV thanks you very much. i didnt know that you could do this this way

**Comment by hif2k1** [comment]
I have added a feature to allow you to input your energy tariff in the latest release. It takes another entity as the input so that we can support variable tariffs, but if there is demand we could support fixed tariffs as well. However, if you are on a fixed tariff it's relatively easy to multiply the total energy by the tariff to work out the money saved.
