### ISSUE TITLE
two imports and 2 exports, but they are not added together.

### ISSUE THREAD

**Issue by bliek79** [hif2k1/battery_sim#80]
first image is of my meter readings;
![image](https://github.com/hif2k1/battery_sim/assets/111599445/3630a2ee-49bf-433e-b3bd-194549761535)
second image is of the meter readings from the battery
![image](https://github.com/hif2k1/battery_sim/assets/111599445/52ca513f-322b-412d-b08a-4fb38f16b393)
in my opinion these should be added together to read the correct values ​​over the long period. would it be possible to adjust this?

regards

**Comment by hif2k1** [comment]
I'm sorry I'm not sure exactly what you mean. 

The battery works to minimise energy being imported and exported. When energy would normally be exported it is stored in the battery instead and any time energy is being imported the battery discharges. However, this isn't always possible. For example when the battery is empty or not able to discharge fast enough to meet the demand some will need to be imported. The "simulated grid import" shows how much energy would still be imported because the batter couldn't meet demand. The same is true for export - not all the energy can be captured e.g. if the battery is full - so any that can't be stored is shown in the simulated grid export. They won't add up to anything relating to the import and export from your utility meter. 

These sensors were added to support including the battery in the home energy dashboard - if you want to include a simulated battery in your dashboard you need to replace the real import and export meters with these simulated ones. 

If I haven't understood what you were saying though do let me know and I will try to understand.

Thanks

**Comment by bliek79** [comment]
I have created combined meters, it’s working better now, 🙏
