### ISSUE TITLE
ate energy dashboard?

### ISSUE THREAD

**Issue by mathieu20152** [hif2k1/battery_sim#92]
Is it normal that the energy dashboard now shows inacurate home usage and solar usage/export?
The last screenshot shows the readings from my P1 meter app
in the energy usage you can see it uses at night 0.7kwh of the battery and import from the grid
![image](https://github.com/hif2k1/battery_sim/assets/66798081/87f3f99e-d12d-4c7e-bec1-9db6d2f2e983)
![image](https://github.com/hif2k1/battery_sim/assets/66798081/26b73e24-d2f9-42a2-9c49-7bccc82269f6)
![image](https://github.com/hif2k1/battery_sim/assets/66798081/47a480e9-ca24-4929-a992-462932865f9e)
![image](https://github.com/hif2k1/battery_sim/assets/66798081/c1318a71-0f82-4d15-9c58-3efdc3e48f51)

**Comment by hif2k1** [comment]
First thing to say is I would not necessarily recommend using a simulated
battery with the energy dashboard as it will change your long term data
about how much energy you are actually using which you might want to look
back on later.

However, if you are going to use it then you need to use the simulated
import and simulated export sensors provided by the relevant battery
instead of your actual import and export sensors. These work out what your
import and export would be if you had the battery. Otherwise the energy
dashboard sees the energy actually coming from the grid and the energy
released from the simulated battery and adds them together.

I can see you have two import and export meters for different tariffs. At
present only a single simulated export and import sensor are provided for
each battery. which will cover both tariff periods. There is already a
request for separate simulated meters which we may look at in due course.

Hope that makes sense.

**Comment by mathieu20152** [comment]
I use the total import/export sensors instead of the tarrifs because I dont let HA calculate the costs because my tarif /KWh changes constantly.  Maybe what I could do aswell is spin up another vm/docker container with just the energie parameters.

**Comment by hif2k1** [comment]
Yes that is the intended use of the simulated import and export sensors.

**Comment by pergolafabio** [comment]
hey @hif2k1 , i did setup this simulator too, if i add the simulated sensors in the dasbboard, i probably need to remove the other original grid/return sensors, but then i dont see any historitical data anymore?
or do i need to add them both?

![image](https://github.com/user-attachments/assets/81174fba-a397-40d0-a3f5-6f72abdf0586)

**Comment by hif2k1** [comment]
Hi there, Yes you would need to remove the real sensors and use the
simulated ones. I don't recommend this, but some users wanted to have it
integrate with the dashboard so I made it possible. Like you I would much
rather keep the energy dashboard for real data, but each to their own. It
does look nice with the battery there.
