### ISSUE TITLE
Statistics_not_defined

### ISSUE THREAD

**Issue by brommetje** [hif2k1/battery_sim#98]
HA 2023.9.2 and 2023.9.3

Just copied everything into configuration.yaml and restart HA

Statistics_not_defined
sensor.sonnen_eco_battery_energy_in
sensor.sonnen_eco_battery_energy_out
 
Entity unavailable
The state of these configured entities are currently not available:
sensor.sonnen_eco_battery_energy_out (unavailable)
sensor.sonnen_eco_battery_energy_in (unavailable)

What do I have to add, doing something wrong?

**Comment by hif2k1** [comment]
Sorry your having an issue. Is this a new setup or was it working before? What is the configuration you are using? Most people use the GUI setup (config flow) now instead of configuration.yaml so maybe we've lost some backwards compatibility along the way. If you create a battery_sim with the GUI does it work?

**Comment by brommetje** [comment]
Hi @hif2k1 it is a new installation just a beginner, so I deleted the stuff in configuraton.yaml, delete the integration, restarted HA and started all over again and configured through the GUI setup now and that works now, thanks for your advise.
